import {
  Activity,
  AppWindow,
  BadgeDollarSign,
  Banknote,
  Bitcoin,
  BriefcaseBusiness,
  Cloud,
  CloudCog,
  Cctv,
  ChartCandlestick,
  ChartColumnIncreasing,
  ChartLine,
  ChartNetwork,
  CircleDollarSign,
  CirclePercent,
  ContactRound,
  CreditCard,
  Database,
  DatabaseBackup,
  DatabaseZap,
  FileBarChart2,
  GitBranchPlus,
  Globe,
  HardDrive,
  HardDriveDownload,
  HardDriveUpload,
  HandCoins,
  KeyRound,
  Landmark,
  Laptop,
  LockKeyhole,
  Monitor,
  Network,
  PackageSearch,
  Router,
  ReceiptText,
  ScanLine,
  Server,
  ServerCog,
  ServerCrash,
  ServerOff,
  Shield,
  ShieldAlert,
  ShieldCheck,
  Smartphone,
  SquareTerminal,
  Tablet,
  UploadCloud,
  Wallet,
  WalletCards,
  Warehouse,
  Waypoints,
  Wifi,
  WifiCog,
  Workflow,
  Printer,
  Cable,
  Cpu,
  Boxes,
  Building2,
} from "lucide-vue-next";

export const TOPOLOGY_ICON_OPTIONS = [
  { label: "无图标", value: "__none__" },
  { label: "服务器", value: "server" },
  { label: "数据库", value: "database" },
  { label: "网络", value: "network" },
  { label: "路由器", value: "router" },
  { label: "防火墙", value: "shield" },
  { label: "云服务", value: "cloud" },
  { label: "Web 应用", value: "app-window" },
  { label: "网站", value: "globe" },
  { label: "存储", value: "hard-drive" },
  { label: "交换/连线", value: "cable" },
  { label: "处理器", value: "cpu" },
  { label: "集群", value: "boxes" },
  { label: "工作流", value: "workflow" },
  { label: "显示器", value: "monitor" },
  { label: "笔记本", value: "laptop" },
  { label: "手机", value: "smartphone" },
  { label: "平板", value: "tablet" },
  { label: "打印机", value: "printer" },
  { label: "Wi-Fi", value: "wifi" },
  { label: "上行网关", value: "upload-cloud" },
  { label: "数据中心", value: "building2" },
  { label: "机房仓储", value: "warehouse" },
  { label: "服务器管理", value: "server-cog" },
  { label: "服务器故障", value: "server-crash" },
  { label: "离线服务器", value: "server-off" },
  { label: "监控摄像头", value: "cctv" },
  { label: "终端控制台", value: "square-terminal" },
  { label: "存储下载", value: "hard-drive-download" },
  { label: "存储上传", value: "hard-drive-upload" },
  { label: "数据库备份", value: "database-backup" },
  { label: "数据库加速", value: "database-zap" },
  { label: "云平台控制", value: "cloud-cog" },
  { label: "链路探测", value: "scan-line" },
  { label: "链路编排", value: "waypoints" },
  { label: "网络优化", value: "wifi-cog" },
  { label: "安全校验", value: "shield-check" },
  { label: "安全告警", value: "shield-alert" },
  { label: "密钥", value: "key-round" },
  { label: "密钥锁", value: "lock-keyhole" },
  { label: "金融机构", value: "landmark" },
  { label: "现金流", value: "banknote" },
  { label: "数字货币", value: "bitcoin" },
  { label: "银行卡", value: "credit-card" },
  { label: "钱包", value: "wallet" },
  { label: "资金账户", value: "wallet-cards" },
  { label: "币种金额", value: "badge-dollar-sign" },
  { label: "金额节点", value: "circle-dollar-sign" },
  { label: "费率/折扣", value: "circle-percent" },
  { label: "清结算", value: "hand-coins" },
  { label: "业务条线", value: "briefcase-business" },
  { label: "业务统计", value: "file-bar-chart-2" },
  { label: "行情趋势", value: "chart-line" },
  { label: "K线分析", value: "chart-candlestick" },
  { label: "指标增长", value: "chart-column-increasing" },
  { label: "业务关系图", value: "chart-network" },
  { label: "流程分支", value: "git-branch-plus" },
  { label: "活跃度", value: "activity" },
  { label: "客户", value: "contact-round" },
  { label: "产品检索", value: "package-search" },
];

export const TOPOLOGY_ICON_COMPONENTS = {
  server: Server,
  database: Database,
  network: Network,
  router: Router,
  shield: Shield,
  cloud: Cloud,
  "app-window": AppWindow,
  globe: Globe,
  "hard-drive": HardDrive,
  cable: Cable,
  cpu: Cpu,
  boxes: Boxes,
  workflow: Workflow,
  monitor: Monitor,
  laptop: Laptop,
  smartphone: Smartphone,
  tablet: Tablet,
  printer: Printer,
  wifi: Wifi,
  "upload-cloud": UploadCloud,
  building2: Building2,
  warehouse: Warehouse,
  "server-cog": ServerCog,
  "server-crash": ServerCrash,
  "server-off": ServerOff,
  cctv: Cctv,
  "square-terminal": SquareTerminal,
  "hard-drive-download": HardDriveDownload,
  "hard-drive-upload": HardDriveUpload,
  "database-backup": DatabaseBackup,
  "database-zap": DatabaseZap,
  "cloud-cog": CloudCog,
  "scan-line": ScanLine,
  waypoints: Waypoints,
  "wifi-cog": WifiCog,
  "shield-check": ShieldCheck,
  "shield-alert": ShieldAlert,
  "key-round": KeyRound,
  "lock-keyhole": LockKeyhole,
  landmark: Landmark,
  banknote: Banknote,
  bitcoin: Bitcoin,
  "credit-card": CreditCard,
  wallet: Wallet,
  "wallet-cards": WalletCards,
  "badge-dollar-sign": BadgeDollarSign,
  "circle-dollar-sign": CircleDollarSign,
  "circle-percent": CirclePercent,
  "hand-coins": HandCoins,
  "briefcase-business": BriefcaseBusiness,
  "file-bar-chart-2": FileBarChart2,
  "chart-line": ChartLine,
  "chart-candlestick": ChartCandlestick,
  "chart-column-increasing": ChartColumnIncreasing,
  "chart-network": ChartNetwork,
  "git-branch-plus": GitBranchPlus,
  activity: Activity,
  "contact-round": ContactRound,
  "package-search": PackageSearch,
};
